version: '3.8'

networks:
  localnet:
    internal: true

services:
  web:
    build: .
    ports:
      - "127.0.0.1:8765:80"
    networks:
      - localnet
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
    tmpfs:
      - /var/run
      - /tmp
      - /tmp/client_temp
